spring:
  profiles:
    active: local
  master:
    datasource:
      username: ${DB_USER_ID}
      password: ${DB_USER_PASSWORD}
      jdbcUrl: jdbc:mysql://${MASTER_DB_IP}:${MASTER_DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
  slave:
    datasource:
      username: ${DB_USER_ID}
      password: ${DB_USER_PASSWORD}
      jdbcUrl: jdbc:mysql://${SLAVE_DB_IP}:${SLAVE_DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      format_sql: true
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER # Swagger-ui
jwt:
  header: Bearer
  secret: ${JWT_SECRET}
  #hs256 algorithm
sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
    callback:
      url: ${GOOGLE_CALLBACK_URL}
    token:
      url: https://oauth2.googleapis.com/token
  github:
    url:
    client:
      id: ${GITHUB_CLIENT_ID}
      secret: ${GITHUB_CLIENT_SECRET}
    callback:
      url: ${GITHUB_CALLBACK_URL}
    token:
      url:
  naver:
    url:
    client:
      id: ${NAVER_CLIENT_ID}
      secret: ${NAVER_CLIENT_SECRET}
    callback:
      url: ${NAVER_CALLBACK_URL}
    token:
      url:
  kakao:
    url:
    client:
      secret: ${KAKAO_CLIENT_SECRET}
    callback:
      url: ${KAKAO_CALLBACK_URL}
    token:
      url:
logging:
  slack:
    webhook-uri: ${WEBHOOK_URL}
  config: classpath:logback-spring.xml
  dir: ${LOG_DIR}